name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 3. Install package and test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: 4. Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 3. Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: 4. Build package
        run: python -m build

      - name: 5. Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: math_utils-dist
          path: dist/